[workspace]
members = [
    "eidoplot",
    "eidoplot-color",
    "eidoplot-dsl",
    "eidoplot-pxl",
    "eidoplot-svg",
    "eidoplot-text",
    "tests",
]
resolver = "3"

[workspace.package]
version = "0.1.0-dev"
authors = ["RÃ©mi THEBAULT"]
edition = "2024"

[workspace.dependencies]
eidoplot = { version = "0.1.0-dev", path = "eidoplot" }
eidoplot-color = { version = "0.1.0-dev", path = "eidoplot-color" }
eidoplot-dsl = { version = "0.1.0-dev", path = "eidoplot-dsl" }
eidoplot-pxl = { version = "0.1.0-dev", path = "eidoplot-pxl" }
eidoplot-svg = { version = "0.1.0-dev", path = "eidoplot-svg" }
eidoplot-text = { version = "0.1.0-dev", path = "eidoplot-text" }
log = "0.4"
rustybuzz = "0.20.1"
tiny-skia = "0.11.4"
tiny-skia-path = "0.11.4"
strict-num = "0.2.0"
miette = "7.6.0"

[workspace.dependencies.ttf-parser]
version = "0.25.1"
default-features = false
features = [
    "opentype-layout",
    "apple-layout",
    "variable-fonts",
    "glyph-names",
    "no-std-float",
]
